paths:
  front_json_dir: /opt/data/private/dataset/3d-front/3D-FRONT/
  future_model_dir: /opt/data/private/dataset/3d-front/3D-FUTURE-model/
  front_texture_dir: /opt/data/private/dataset/3d-front/3D-FRONT-texture/
  output_dir: ./output/3df/

selection:
  seed: 0
  shuffle: false
  max_scenes: null
  scene_names: []

logic:
  num_views: 5
  max_tries: 30000
  lens: 50
  height_min: 1.4
  height_max: 1.8
  pitch_min: 1.2217
  pitch_max: 1.338
  coverage_score_min: 0.65
  proximity_min: 0.5
  proximity_avg_min: 1.5
  proximity_avg_max: 5.0
  proximity_no_background: true
  special_object_names: ["chair", "sofa", "table", "bed"]

render:
  device: GPU
  gpu_backend: OPTIX
  gpu_indices: [0]
  samples_max: 128
  noise_threshold: 0.03
  use_denoising: true
  denoiser: OPTIX
  res_x: 1024
  res_y: 768
  light_paths:
    max_bounces: 8
    diffuse_bounces: 4
    glossy_bounces: 4
    transparent_max: 8
    transmission: 8
  outputs:
    depth: false
    normals: false
    segmentation: false
    segmentation_map_by: ["category_id"]
