paths:
  front_json_dir: /opt/data/private/dataset/3d-front/3D-FRONT/
  future_model_dir: /opt/data/private/dataset/3d-front/3D-FUTURE-model/
  front_texture_dir: /opt/data/private/dataset/3d-front/3D-FRONT-texture/
  output_dir: ./output/3df/

selection:
  seed: 0
  shuffle: false
  max_scenes: null
  scene_names: []

logic:
  num_views: 10
  max_tries: 10000
  lens: 50
  height_min: 1.4
  height_max: 1.8
  pitch_min: 1.2217
  pitch_max: 1.338
  coverage_score_min: 0.8
  proximity_min: 1.0
  proximity_avg_min: 2.5
  proximity_avg_max: 3.5
  proximity_no_background: true
  special_object_names: ["chair", "sofa", "table", "bed"]

render:
  res_x: 1600
  res_y: 1200
  light_paths:
    max_bounces: 200
    diffuse_bounces: 200
    glossy_bounces: 200
    transparent_max: 200
    transmission: 200
  outputs:
    depth: false
    normals: true
    segmentation: true
    segmentation_map_by: ["category_id"]
