import blenderproc as bproc

import argparse
import csv
import importlib.util
import json
import math
import os
from pathlib import Path

import numpy as np
from PIL import Image


def _load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Failed to load module from {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_HERE = Path(__file__).resolve().parent
render_mod = _load_module("front3d_place_and_render", _HERE / "front3d_place_and_render.py")
render_profile = render_mod.render_profile
lamp_lighting = _load_module("lamp_lighting", _HERE / "lamp_lighting.py")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Render inspection views around a prescan placement point without placing the target object."
    )
    parser.add_argument(
        "--placement-file",
        default="./prescan_locations.csv",
        help="CSV generated by export_prescan_locations.py",
    )
    parser.add_argument(
        "--placement-id",
        type=int,
        default=0,
        help="placement_id in the placement file to inspect.",
    )
    parser.add_argument(
        "--front-json-name",
        default=None,
        help="Optional scene file name to select instead of placement_id.",
    )
    parser.add_argument(
        "--front-json-dir",
        default=None,
        help="Override front_json_dir from config.",
    )
    parser.add_argument(
        "--future-model-dir",
        default=None,
        help="Override future_model_dir from config.",
    )
    parser.add_argument(
        "--front-texture-dir",
        default=None,
        help="Override front_texture_dir from config.",
    )
    parser.add_argument(
        "--output-root",
        default=None,
        help="Root directory for inspection outputs. Defaults to output_dir from config.",
    )
    parser.add_argument(
        "--num-views",
        type=int,
        default=4,
        help="Number of horizontal orbit views around the placement point.",
    )
    parser.add_argument(
        "--camera-distance",
        type=float,
        default=0.0,
        help="Horizontal distance to the placement point in meters. <=0 means auto from sphere_radius.",
    )
    parser.add_argument(
        "--distance-factor",
        type=float,
        default=0.8,
        help="When camera-distance <= 0, use sphere_radius * distance_factor.",
    )
    parser.add_argument(
        "--min-camera-distance",
        type=float,
        default=0.8,
        help="Lower bound for auto camera distance.",
    )
    parser.add_argument(
        "--max-camera-distance",
        type=float,
        default=3.0,
        help="Upper bound for auto camera distance.",
    )
    parser.add_argument(
        "--camera-height-offset",
        type=float,
        default=0.15,
        help="Vertical offset above the placement point for horizontal orbit cameras.",
    )
    parser.add_argument(
        "--include-top-view",
        action="store_true",
        help="Also render one top-down overview.",
    )
    parser.add_argument(
        "--top-view-height",
        type=float,
        default=1.8,
        help="Top-down camera height above the placement point.",
    )
    parser.add_argument(
        "--marker-radius",
        type=float,
        default=0.05,
        help="Radius of the red debug sphere marking the placement point. 0 disables the marker.",
    )
    parser.add_argument(
        "--marker-color",
        type=float,
        nargs=3,
        default=(1.0, 0.1, 0.1),
        help="Marker base color as R G B in 0..1.",
    )
    return parser.parse_args()


def _safe_float(value, name):
    try:
        return float(value)
    except Exception as exc:
        raise ValueError(f"Invalid numeric value for {name}: {value}") from exc


def _load_csv_rows(path):
    with open(path, newline="", encoding="utf-8-sig") as file:
        sample = file.read(4096)
        file.seek(0)

        try:
            dialect = csv.Sniffer().sniff(sample, delimiters=",\t;")
        except csv.Error:
            dialect = csv.excel

        reader = csv.DictReader(file, dialect=dialect)
        if not reader.fieldnames:
            raise RuntimeError(f"No header found in placement file: {path}")

        fieldnames = [name.strip() if name is not None else name for name in reader.fieldnames]
        rows = []
        for row_index, row in enumerate(reader):
            clean_row = {}
            for key, value in row.items():
                if key is None:
                    continue
                clean_row[key.strip()] = value.strip() if isinstance(value, str) else value
            if "placement_id" not in clean_row:
                clean_row["placement_id"] = str(row_index)
            rows.append(clean_row)

    return fieldnames, rows


def load_placement(placement_file, placement_id, front_json_name):
    _, rows = _load_csv_rows(placement_file)
    if not rows:
        raise RuntimeError(f"No rows in placement file: {placement_file}")

    if front_json_name:
        for row in rows:
            if row.get("front_json") == front_json_name:
                return row
        raise KeyError(f"front_json not found in placement file: {front_json_name}")

    for row in rows:
        try:
            current_id = int(row.get("placement_id", -1))
        except Exception:
            current_id = -1
        if current_id == placement_id:
            return row
    raise KeyError(f"placement_id not found in placement file: {placement_id}")


def resolve_paths(args, placement):
    config = render_profile.PATHS_CONFIG
    front_json_dir = args.front_json_dir or config.get("front_json_dir")
    future_model_dir = args.future_model_dir or config.get("future_model_dir")
    front_texture_dir = args.front_texture_dir or config.get("front_texture_dir")
    output_root = args.output_root or config.get("output_dir")

    if not front_json_dir:
        raise ValueError("Missing front_json_dir")
    front_json = placement["front_json"]
    if not os.path.isabs(front_json):
        front_json = os.path.join(front_json_dir, front_json)

    for path in [front_json, future_model_dir, front_texture_dir]:
        if not path or not os.path.exists(path):
            raise FileNotFoundError(path)

    scene_stem = Path(front_json).stem
    placement_label = placement.get("placement_id", "unknown")
    output_dir = os.path.join(output_root, f"{scene_stem}__placement_{placement_label}__inspection")
    os.makedirs(output_dir, exist_ok=True)

    return {
        "front_json": front_json,
        "future_model_dir": future_model_dir,
        "front_texture_dir": front_texture_dir,
        "output_dir": output_dir,
    }


def choose_camera_distance(args, placement):
    if args.camera_distance > 0:
        return float(args.camera_distance)

    sphere_radius = _safe_float(placement["sphere_radius"], "sphere_radius")
    camera_distance = sphere_radius * float(args.distance_factor)
    camera_distance = max(float(args.min_camera_distance), camera_distance)
    camera_distance = min(float(args.max_camera_distance), camera_distance)
    return camera_distance


def add_debug_marker(target_point, radius, color_rgb):
    if radius <= 0:
        return None

    marker = bproc.object.create_primitive("ICO_SPHERE", radius=radius, location=target_point.tolist())
    marker.set_name("PrescanMarker")
    marker.set_shading_mode("SMOOTH")
    mat = marker.new_material("PrescanMarkerMaterial")
    mat.set_principled_shader_value("Base Color", list(color_rgb) + [1.0])
    mat.make_emissive(
        emission_strength=5.0,
        emission_color=list(color_rgb) + [1.0],
    )
    return marker


def _cardinal_label(index, num_views):
    if num_views == 4:
        return ["front", "right", "back", "left"][index]
    return f"orbit_{index:02d}"


def build_camera_poses(target_point, camera_distance, camera_height_offset, num_views, include_top_view, top_view_height):
    camera_entries = []

    for idx in range(num_views):
        angle = (2.0 * math.pi * idx) / num_views
        cam_location = np.array(
            [
                target_point[0] + camera_distance * math.cos(angle),
                target_point[1] + camera_distance * math.sin(angle),
                target_point[2] + camera_height_offset,
            ],
            dtype=float,
        )
        toward_direction = target_point - cam_location
        rotation_matrix = bproc.camera.rotation_from_forward_vec(toward_direction, inplane_rot=0.0)
        cam2world_matrix = bproc.math.build_transformation_mat(cam_location, rotation_matrix)
        bproc.camera.add_camera_pose(np.array(cam2world_matrix))
        camera_entries.append(
            {
                "name": _cardinal_label(idx, num_views),
                "location": cam_location.tolist(),
                "transform_matrix": np.asarray(cam2world_matrix).tolist(),
            }
        )

    if include_top_view:
        cam_location = np.array(
            [target_point[0], target_point[1], target_point[2] + top_view_height],
            dtype=float,
        )
        toward_direction = target_point - cam_location
        rotation_matrix = bproc.camera.rotation_from_forward_vec(toward_direction, inplane_rot=0.0)
        cam2world_matrix = bproc.math.build_transformation_mat(cam_location, rotation_matrix)
        bproc.camera.add_camera_pose(np.array(cam2world_matrix))
        camera_entries.append(
            {
                "name": "top",
                "location": cam_location.tolist(),
                "transform_matrix": np.asarray(cam2world_matrix).tolist(),
            }
        )

    return camera_entries


def save_color_images(output_dir, camera_entries, colors):
    for idx, (entry, img) in enumerate(zip(camera_entries, colors)):
        filename = f"{idx:03d}_{entry['name']}.png"
        Image.fromarray(np.asarray(img).astype(np.uint8)).save(os.path.join(output_dir, filename))
        entry["image_file"] = filename


def write_metadata(output_dir, placement, target_point, camera_distance, args, camera_entries):
    metadata = {
        "placement": dict(placement),
        "target_point": target_point.tolist(),
        "camera_distance": camera_distance,
        "camera_height_offset": args.camera_height_offset,
        "include_top_view": bool(args.include_top_view),
        "top_view_height": args.top_view_height,
        "marker_radius": args.marker_radius,
        "camera_entries": camera_entries,
    }
    with open(os.path.join(output_dir, "inspection_metadata.json"), "w", encoding="utf-8") as file:
        json.dump(metadata, file, indent=2)


def main():
    args = parse_args()
    if args.num_views <= 0:
        raise ValueError("--num-views must be >= 1")
    if args.top_view_height <= 0:
        raise ValueError("--top-view-height must be > 0")

    placement = load_placement(args.placement_file, args.placement_id, args.front_json_name)
    paths = resolve_paths(args, placement)

    target_point = np.array(
        [
            _safe_float(placement["pos_x"], "pos_x"),
            _safe_float(placement["pos_y"], "pos_y"),
            _safe_float(placement["pos_z"], "pos_z"),
        ],
        dtype=float,
    )
    camera_distance = choose_camera_distance(args, placement)

    bproc.init()

    mapping_file = bproc.utility.resolve_resource(os.path.join("front_3D", "3D_front_mapping.csv"))
    mapping = bproc.utility.LabelIdMapping.from_csv(mapping_file)

    bproc.renderer.set_light_bounces(
        diffuse_bounces=200,
        glossy_bounces=200,
        max_bounces=200,
        transmission_bounces=200,
        transparent_max_bounces=200,
    )

    room_objs = bproc.loader.load_front3d(
        json_path=paths["front_json"],
        future_model_path=paths["future_model_dir"],
        front_3D_texture_path=paths["front_texture_dir"],
        label_mapping=mapping,
        lamp_light_strength=0,
    )
    lamp_lighting.apply_lighting_to_scene(room_objs, paths["front_json"])

    render_profile.setup_render_settings()
    bproc.camera.set_intrinsics_from_blender_params(
        lens=render_profile.LOGIC_CONFIG["lens"],
        image_width=render_profile.RENDER_CONFIG["res_x"],
        image_height=render_profile.RENDER_CONFIG["res_y"],
    )

    add_debug_marker(target_point, args.marker_radius, args.marker_color)

    camera_entries = build_camera_poses(
        target_point=target_point,
        camera_distance=camera_distance,
        camera_height_offset=float(args.camera_height_offset),
        num_views=int(args.num_views),
        include_top_view=bool(args.include_top_view),
        top_view_height=float(args.top_view_height),
    )

    data = bproc.renderer.render()
    colors = data.get("colors")
    if colors is None:
        raise RuntimeError("Renderer did not return colors output.")

    save_color_images(paths["output_dir"], camera_entries, colors)
    write_metadata(paths["output_dir"], placement, target_point, camera_distance, args, camera_entries)

    print(f"Rendered inspection for placement_id={placement.get('placement_id', 'unknown')}")
    print(f"Scene: {placement['front_json']}")
    print(f"Support: {placement.get('support_name', '')}")
    print(f"Output: {paths['output_dir']}")


if __name__ == "__main__":
    main()
