import blenderproc as bproc

import argparse
import csv
import importlib.util
import math
import os
from pathlib import Path

import bpy
import numpy as np
from mathutils import Vector


def _load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Failed to load module from {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_HERE = Path(__file__).resolve().parent
render_mod = _load_module("front3d_place_and_render", _HERE / "front3d_place_and_render.py")
render_profile = render_mod.render_profile


def parse_args():
    parser = argparse.ArgumentParser(
        description="Render a scene using a fixed placement exported from prescan CSVs."
    )
    parser.add_argument(
        "--placement-file",
        default="./prescan_locations.csv",
        help="CSV generated by export_prescan_locations.py",
    )
    parser.add_argument(
        "--placement-id",
        type=int,
        default=0,
        help="placement_id in the placement file to render.",
    )
    parser.add_argument(
        "--front-json-name",
        default=None,
        help="Optional scene file name to select instead of placement_id.",
    )
    parser.add_argument(
        "--front-json-dir",
        default=None,
        help="Override front_json_dir from config.",
    )
    parser.add_argument(
        "--future-model-dir",
        default=None,
        help="Override future_model_dir from config.",
    )
    parser.add_argument(
        "--front-texture-dir",
        default=None,
        help="Override front_texture_dir from config.",
    )
    parser.add_argument(
        "--object-path",
        default=None,
        help="Override object_path from config.",
    )
    parser.add_argument(
        "--output-root",
        default=None,
        help="Root directory for render outputs. Defaults to output_dir from config.",
    )
    parser.add_argument(
        "--target-max-size",
        type=float,
        default=0.40,
        help="Scale the custom object so its largest bbox dimension matches this size in meters.",
    )
    return parser.parse_args()


def _safe_float(value, name):
    try:
        return float(value)
    except Exception as exc:
        raise ValueError(f"Invalid numeric value for {name}: {value}") from exc


def load_placement(placement_file, placement_id, front_json_name):
    with open(placement_file, newline="", encoding="utf-8") as file:
        rows = list(csv.DictReader(file))
    if not rows:
        raise RuntimeError(f"No rows in placement file: {placement_file}")

    if front_json_name:
        for row in rows:
            if row.get("front_json") == front_json_name:
                return row
        raise KeyError(f"front_json not found in placement file: {front_json_name}")

    for row in rows:
        try:
            current_id = int(row.get("placement_id", -1))
        except Exception:
            current_id = -1
        if current_id == placement_id:
            return row
    raise KeyError(f"placement_id not found in placement file: {placement_id}")


def resolve_paths(args, placement):
    config = render_profile.PATHS_CONFIG
    front_json_dir = args.front_json_dir or config.get("front_json_dir")
    future_model_dir = args.future_model_dir or config.get("future_model_dir")
    front_texture_dir = args.front_texture_dir or config.get("front_texture_dir")
    object_path = args.object_path or config.get("object_path")
    output_root = args.output_root or config.get("output_dir")

    if not front_json_dir:
        raise ValueError("Missing front_json_dir")
    front_json = placement["front_json"]
    if not os.path.isabs(front_json):
        front_json = os.path.join(front_json_dir, front_json)

    paths = {
        "front_json": front_json,
        "future_model_dir": future_model_dir,
        "front_texture_dir": front_texture_dir,
        "object_path": object_path,
    }
    render_mod.validate_paths(paths)

    scene_stem = Path(front_json).stem
    placement_label = placement.get("placement_id", "unknown")
    output_dir = os.path.join(output_root, f"{scene_stem}__placement_{placement_label}")
    os.makedirs(output_dir, exist_ok=True)

    paths["output_dir"] = output_dir
    return paths


def find_support_object(room_objs, support_name):
    for obj in room_objs:
        if obj.get_name() == support_name:
            return obj
    raise KeyError(f"Support object not found in loaded scene: {support_name}")


def place_object_with_fixed_location(custom_obj, support_obj, room_objs, placement):
    support_name = support_obj.get_name()
    pos_x = _safe_float(placement["pos_x"], "pos_x")
    pos_y = _safe_float(placement["pos_y"], "pos_y")
    pos_z = _safe_float(placement["pos_z"], "pos_z")
    custom_obj.set_location(np.array((pos_x, pos_y, pos_z), dtype=float))

    if render_profile.LOGIC_CONFIG.get("use_physics", False):
        custom_obj.enable_rigidbody(True, collision_shape="CONVEX_HULL")
        support_obj.enable_rigidbody(False)
        bproc.object.simulate_physics_and_fix_final_poses(
            min_simulation_time=2,
            max_simulation_time=4,
            check_object_interval=1,
        )

    return {
        "ok": True,
        "support_name": support_name,
        "surface_name": "",
        "center_z": pos_z,
    }


def maybe_rescale_to_sphere_radius(custom_obj, sphere_radius, scale_factor):
    if sphere_radius is None:
        return scale_factor

    target_diameter = float(render_profile.LOGIC_CONFIG["target_diameter"])
    margin = float(render_profile.LOGIC_CONFIG["margin"])
    cam_data = bpy.data.cameras.get("UltraCam") or bpy.data.cameras.new("UltraCam")
    cam_data.lens = render_profile.LOGIC_CONFIG["lens"]
    fov_h = cam_data.angle
    aspect_ratio = render_profile.RENDER_CONFIG["res_x"] / render_profile.RENDER_CONFIG["res_y"]
    fov_v = 2 * math.atan(math.tan(fov_h / 2) / aspect_ratio)
    ideal_diameter = 2 * sphere_radius * math.sin(min(fov_h, fov_v) / 2) / margin
    current_bbox = custom_obj.get_bound_box()
    current_size = float(np.max(np.max(current_bbox, axis=0) - np.min(current_bbox, axis=0)))
    if current_size <= 0:
        return scale_factor

    current_loc = np.array(custom_obj.get_location(), dtype=float)
    rescale = ideal_diameter / current_size
    custom_obj.set_scale(np.array(custom_obj.blender_obj.scale) * rescale)
    custom_obj.persist_transformation_into_mesh(location=False, rotation=False, scale=True)
    custom_obj.set_location(current_loc)
    return scale_factor * rescale


def add_camera_poses_float_mode(anchor_obj, target_obj, sphere_radius):
    render_profile.setup_render_settings()

    scene = bpy.context.scene
    cam_obj = render_profile.create_smart_camera(anchor_obj.blender_obj)
    bproc.camera.set_intrinsics_from_blender_params(
        lens=render_profile.LOGIC_CONFIG["lens"],
        image_width=render_profile.RENDER_CONFIG["res_x"],
        image_height=render_profile.RENDER_CONFIG["res_y"],
    )

    target_bbox = target_obj.get_bound_box()
    target_location = np.mean(target_bbox, axis=0)

    if sphere_radius is not None:
        camera_distance = float(sphere_radius)
    else:
        target_radius = render_profile.LOGIC_CONFIG["target_diameter"] / 2.0
        margin = render_profile.LOGIC_CONFIG["margin"]
        fov_h = cam_obj.data.angle
        aspect_ratio = scene.render.resolution_x / scene.render.resolution_y
        fov_v = 2 * math.atan(math.tan(fov_h / 2) / aspect_ratio)
        camera_distance = (target_radius * margin) / math.sin(min(fov_h, fov_v) / 2)

    candidate_count = int(render_profile.LOGIC_CONFIG["num_views"])
    camera_positions_local = render_profile.generate_fibonacci_points(
        n_samples=candidate_count,
        radius=camera_distance,
        center_loc=Vector((0, 0, 0)),
        hemisphere=render_profile.LOGIC_CONFIG["use_hemisphere"],
    )

    for pos_local in camera_positions_local:
        cam_location = np.array(pos_local + anchor_obj.blender_obj.location, dtype=float)
        toward_direction = target_location - cam_location
        rotation_matrix = bproc.camera.rotation_from_forward_vec(toward_direction, inplane_rot=0.0)
        cam2world_matrix = bproc.math.build_transformation_mat(cam_location, rotation_matrix)
        bproc.camera.add_camera_pose(np.array(cam2world_matrix))

    return candidate_count


def add_camera_poses_with_fallback(anchor, custom_obj, room_objs, sphere_radius):
    try:
        return render_mod.add_batch_render_camera_poses(
            anchor, custom_obj, room_objs + [custom_obj], sphere_radius=sphere_radius
        )
    except RuntimeError as exc:
        if "No valid camera pose found" not in str(exc):
            raise
        return render_mod.add_batch_render_camera_poses(
            anchor, custom_obj, room_objs + [custom_obj], sphere_radius=None
        )


def main():
    args = parse_args()
    placement = load_placement(args.placement_file, args.placement_id, args.front_json_name)
    paths = resolve_paths(args, placement)

    bproc.init()

    mapping_file = bproc.utility.resolve_resource(os.path.join("front_3D", "3D_front_mapping.csv"))
    mapping = bproc.utility.LabelIdMapping.from_csv(mapping_file)

    bproc.renderer.set_light_bounces(
        diffuse_bounces=200,
        glossy_bounces=200,
        max_bounces=200,
        transmission_bounces=200,
        transparent_max_bounces=200,
    )

    room_objs = bproc.loader.load_front3d(
        json_path=paths["front_json"],
        future_model_path=paths["future_model_dir"],
        front_3D_texture_path=paths["front_texture_dir"],
        label_mapping=mapping,
        lamp_light_strength=0,
    )

    lamp_lighting = _load_module("lamp_lighting", _HERE / "lamp_lighting.py")
    lamp_lighting.apply_lighting_to_scene(room_objs, paths["front_json"])

    support_obj = find_support_object(room_objs, placement["support_name"])

    custom_obj = render_mod.load_custom_object(paths["object_path"])
    scale_factor = render_mod.scale_object_to_target_size(custom_obj, args.target_max_size)

    placement_info = place_object_with_fixed_location(custom_obj, support_obj, room_objs, placement)
    sphere_radius = _safe_float(placement["sphere_radius"], "sphere_radius")
    if not placement_info["ok"]:
        custom_obj.delete()
        raise RuntimeError(
            f"Failed to place object from placement file: {placement_info.get('reason', 'unknown')}"
        )

    scale_factor = maybe_rescale_to_sphere_radius(custom_obj, sphere_radius, scale_factor)

    render_mod.apply_batch_render_material_strategy(custom_obj, paths["object_path"])

    anchor = bproc.object.create_primitive("CUBE")
    anchor.set_name("ANCHOR")
    anchor.hide(True)
    anchor.set_location(np.mean(custom_obj.get_bound_box(), axis=0))

    camera_count = add_camera_poses_float_mode(anchor, custom_obj, sphere_radius)

    bproc.renderer.enable_depth_output(activate_antialiasing=False)
    bproc.renderer.enable_normals_output()
    bproc.renderer.enable_segmentation_output(map_by=["category_id", "instance", "name"])

    data = bproc.renderer.render()
    data = render_mod.add_binary_mask_from_category_id(data, target_category_id=999)
    bproc.writer.write_hdf5(paths["output_dir"], data)

    render_mod.write_metadata(
        output_dir=paths["output_dir"],
        front_json=paths["front_json"],
        object_path=paths["object_path"],
        support_name=placement_info["support_name"],
        surface_name=placement_info["surface_name"],
        scale_factor=scale_factor,
        camera_count=camera_count,
        placement_mode="prescan_float",
        sphere_radius=sphere_radius,
    )

    print(f"Rendered placement_id={placement.get('placement_id', 'unknown')}")
    print(f"Scene: {placement['front_json']}")
    print(f"Support: {placement['support_name']}")
    print(f"Output: {paths['output_dir']}")


if __name__ == "__main__":
    main()
